<!DOCTYPE html>
<html>
<head>
    <title>Reimbursement Proof</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #0891b2; padding-bottom: 10px; }
        .title { font-size: 20px; font-weight: bold; margin-bottom: 5px; color: #0891b2; }
        .subtitle { color: #666; font-size: 10px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; vertical-align: top; }
        th { background-color: #f0f9ff; color: #333; font-weight: bold; width: 30%; }
        .success { color: green; font-weight: bold; }
        .signature-img { max-height: 50px; max-width: 100px; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 10px; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">REIMBURSEMENT CLAIM PROOF</div>
        <div class="subtitle">Generated by SOBAT-HR on {{ now()->format('d M Y H:i') }}</div>
    </div>

    <h3>Request Information</h3>
    <table>
        <tr>
            <th>Request No</th>
            <td>REQ-{{ str_pad($request->id, 5, '0', STR_PAD_LEFT) }}</td>
        </tr>
        <tr>
            <th>Requester Name</th>
            <td>
                <strong>{{ $request->employee->full_name ?? 'Unknown' }}</strong><br>
                <small>{{ $request->employee->employee_code ?? '-' }} / {{ $request->employee->position ?? '-' }}</small>
            </td>
        </tr>
        <tr>
            <th>Submission Date</th>
            <td>{{ $request->created_at->format('d F Y') }}</td>
        </tr>
         <tr>
            <th>Status</th>
            <td>{{ strtoupper($request->status) }}</td>
        </tr>
    </table>

    <h3>Claim Details</h3>
    <table>
        <tr>
            <th>Category / Title</th>
            <td>{{ $request->title }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ $request->description }}</td>
        </tr>
        <tr>
            <th>Date of Expense</th>
            <td>{{ $request->start_date ? $request->start_date->format('d F Y') : '-' }}</td>
        </tr>
        <tr>
            <th>Total Amount</th>
            <td>
               <span style="font-size: 14px; font-weight: bold;">Rp {{ number_format($request->amount ?? 0, 0, ',', '.') }}</span>
            </td>
        </tr>
    </table>

    <h3>Receipts / Attachments</h3>
    <div style="margin-bottom: 20px; border: 1px solid #ddd; padding: 10px; min-height: 100px;">
        @if(!empty($request->attachments))
             @php
                $att = $request->attachments;
                if(is_string($att)) $att = json_decode($att, true);
                if(!is_array($att)) $att = [$att];
            @endphp
            
            <div style="display: block; text-align: center;">
            @foreach($att as $img)
                @if($img && str_contains($img, 'data:image'))
                    <img src="{{ $img }}" style="max-width: 90%; max-height: 400px; margin-bottom: 10px; border: 1px solid #eee; padding: 5px;">
                @elseif($img)
                    <p><a href="{{ $img }}" target="_blank">View External Attachment</a></p>
                @endif
            @endforeach
            </div>
        @else
            <p style="text-align: center; color: #999;">No Receipts Attached</p>
        @endif
    </div>

    <div style="page-break-inside: avoid;">
    <h3>Approval Timeline</h3>
    <table>
        <thead>
            <tr>
                <th style="width:15%">Level</th>
                <th style="width:35%">Approver</th>
                <th style="width:15%">Status</th>
                <th style="width:20%">Date</th>
                <th style="width:15%">Signature</th>
            </tr>
        </thead>
        <tbody>
            @foreach($request->approvals as $approval)
            <tr>
                <td>Level {{ $approval->level }}</td>
                <td>
                    @php
                        $approverName = $approval->approver->full_name ?? 'Unknown';
                        $displayPosition = $approval->approver->position ?? '';
                        if ($approval->note && preg_match('/Approved by[:\s]+(.*)/i', $approval->note, $matches)) {
                             $extractedName = trim($matches[1]);
                             if (strtolower($extractedName) !== 'system/user') {
                                 $approverName = $extractedName;
                             }
                        }
                    @endphp
                    <strong>{{ $approverName }}</strong><br>
                    <small>{{ $displayPosition }}</small>
                </td>
                <td class="{{ $approval->status == 'approved' ? 'success' : '' }}">
                    {{ ucfirst($approval->status) }}
                </td>
                <td>
                    {{ $approval->acted_at ? \Carbon\Carbon::parse($approval->acted_at)->format('d M Y H:i') : '-' }}
                </td>
                <td style="text-align:center;">
                    @php
                        $sig = $approval->signature;
                        if (!empty($sig) && !str_contains($sig, 'data:image')) {
                            $sig = 'data:image/png;base64,' . $sig;
                        }
                    @endphp
                    @if(!empty($sig) && str_contains($sig, 'data:image'))
                        <img src="{{ $sig }}" class="signature-img">
                    @elseif($approval->status == 'approved')
                        <span style="font-size:10px; color:#999;">Digital Signed</span>
                    @else
                        -
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    </div>
    
    <div style="margin-top: 30px; text-align: center; font-size: 9px; color: #999;">
        This document is valid proof of reimbursement claim approval.<br>
        Date Printed: {{ now()->format('d M Y') }}
    </div>
</body>
</html>
