<!DOCTYPE html>
<html>
<head>
    <title>Asset Request Proof</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #462e37; padding-bottom: 10px; }
        .title { font-size: 20px; font-weight: bold; margin-bottom: 5px; color: #462e37; }
        .subtitle { color: #666; font-size: 10px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; vertical-align: top; }
        th { background-color: #f8f9fa; color: #333; font-weight: bold; width: 30%; }
        .success { color: green; font-weight: bold; }
        .signature-img { max-height: 50px; max-width: 100px; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 10px; font-weight: bold; }
        .badge-urgent { background-color: #fee2e2; color: #b91c1c; }
        .badge-regular { background-color: #dcfce7; color: #15803d; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">ASSET SUBMISSION PROOF</div>
        <div class="subtitle">Generated by SOBAT-HR on {{ now()->format('d M Y H:i') }}</div>
    </div>

    <h3>Request Information</h3>
    <table>
        <tr>
            <th>Request No</th>
            <td>REQ-{{ str_pad($request->id, 5, '0', STR_PAD_LEFT) }}</td>
        </tr>
        <tr>
            <th>Requester Name</th>
            <td>
                <strong>{{ $request->employee->full_name ?? 'Unknown' }}</strong><br>
                <small>{{ $request->employee->employee_code ?? '-' }} / {{ $request->employee->position ?? '-' }}</small>
            </td>
        </tr>
        <tr>
            <th>Submission Date</th>
            <td>{{ $request->created_at->format('d F Y') }}</td>
        </tr>
         <tr>
            <th>Status</th>
            <td>
                <span class="badge {{ $request->status == 'approved' ? 'badge-regular' : 'badge-urgent' }}" style="background:none; color:black; border:1px solid #ccc; font-size:12px;">
                    {{ strtoupper($request->status) }}
                </span>
            </td>
        </tr>
    </table>

    <h3>Asset Details</h3>
    <table>
        <tr>
            <th>Brand / Item Name</th>
            <td>{{ $request->detail['brand'] ?? '-' }}</td>
        </tr>
        <tr>
            <th>Specification</th>
            <td>{{ $request->detail['specification'] ?? '-' }}</td>
        </tr>
        <tr>
            <th>Estimated Price</th>
            <td>
               Rp {{ number_format($request->amount ?? 0, 0, ',', '.') }}
            </td>
        </tr>
        <tr>
            <th>Urgency</th>
            <td>
                @if(($request->detail['is_urgent'] ?? false))
                    <span class="badge badge-urgent">URGENT</span>
                @else
                    <span class="badge badge-regular">REGULAR</span>
                @endif
            </td>
        </tr>
        <tr>
            <th>Description / Reason</th>
            <td>{{ $request->description }}</td>
        </tr>
    </table>

    @if(!empty($request->attachments))
    <h3>Attachment</h3>
    <div style="margin-bottom: 20px; border: 1px solid #ddd; padding: 10px; text-align:center;">
        @php
            $att = $request->attachments;
            if(is_string($att)) $att = json_decode($att, true);
            $firstImg = is_array($att) ? ($att[0] ?? null) : null;
        @endphp
        
        @if($firstImg && str_contains($firstImg, 'data:image'))
            <img src="{{ $firstImg }}" style="max-width: 100%; max-height: 300px;">
        @elseif($firstImg)
             <a href="{{ $firstImg }}">View Attachment</a>
        @else
             No Attachment
        @endif
    </div>
    @endif

    <div style="page-break-inside: avoid;">
        <h3>Approval Timeline</h3>
        <table>
            <thead>
                <tr>
                    <th style="width:15%">Level</th>
                    <th style="width:35%">Approver</th>
                    <th style="width:15%">Status</th>
                    <th style="width:20%">Date</th>
                    <th style="width:15%">Signature</th>
                </tr>
            </thead>
            <tbody>
                @foreach($request->approvals as $approval)
                <tr>
                    <td>Level {{ $approval->level }}</td>
                    <td>
                        @php
                            $approverName = $approval->approver->full_name ?? 'Unknown';
                            $displayPosition = $approval->approver->position ?? '';
                             // Check for Admin Override Name in Note
                            if ($approval->note && preg_match('/Approved by[:\s]+(.*)/i', $approval->note, $matches)) {
                                 $extractedName = trim($matches[1]);
                                 if (strtolower($extractedName) !== 'system/user') {
                                     $approverName = $extractedName;
                                 }
                            }
                        @endphp
                        <strong>{{ $approverName }}</strong><br>
                        <small>{{ $displayPosition }}</small>
                    </td>
                    <td class="{{ $approval->status == 'approved' ? 'success' : '' }}">
                        {{ ucfirst($approval->status) }}
                    </td>
                    <td>
                        {{ $approval->acted_at ? \Carbon\Carbon::parse($approval->acted_at)->format('d M Y H:i') : '-' }}
                    </td>
                    <td style="text-align:center;">
                        @php
                            $sig = $approval->signature;
                            if (!empty($sig) && !str_contains($sig, 'data:image')) {
                                $sig = 'data:image/png;base64,' . $sig;
                            }
                        @endphp
                        @if(!empty($sig) && str_contains($sig, 'data:image'))
                            <img src="{{ $sig }}" class="signature-img">
                        @elseif($approval->status == 'approved')
                            <span style="font-size:10px; color:#999;">Digital Signed</span>
                        @else
                            -
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    
    <div style="margin-top: 30px; text-align: center; font-size: 9px; color: #999;">
        This document is automatically generated by the SOBAT-HR System and is valid without a wet signature.<br>
        Date Printed: {{ now()->format('d M Y') }}
    </div>
</body>
</html>
